### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mrtanishqbhatia** [sebasanger/sprintel#1]
Hello,

I am following this git repository to learn about Spring boot JWT authentication. Would you mind setting up just a README for basic CRUD requests format? (Register/login, update, delete user)

Thanks.

**Comment by sebasanger** [comment]
Hello @mrtanishqbhatia ,

Here you have the documentation with postman https://documenter.getpostman.com/view/9041469/TzK2ZZ1c

For JTW you need pass the BEARER TOKEN create by server in every request, i make this with interceptors on angular.

**Comment by mrtanishqbhatia** [comment]
Thanks.
